version: '3'

services:
  chart-module:
    build: ./
    depends_on:
      - 'mongodb'
    ports:
      - '3001:3001'

  seeder:
    build: ./db
    depends_on:
      - 'mongodb'

  mongodb:
    image: mongo:latest
