version: '3'

services:
  chart-module:
    image: seungprk/chart-module:latest
    depends_on:
      - 'mongodb'
    ports:
      - '80:3001'
    environment:
      - NODE_DB=mongodb://mongodb/front_end_capstone
  seeder:
    image: seungprk/seeder:latest
    depends_on:
      - "mongodb"

  mongodb:
    image: mongo:latest

